stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: latest
  IMAGE_NAME: booking-service

build:
  stage: build
  script:


test:
  stage: test
  script:


deploy:
  stage: deploy
  script:
 