apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-v1
  labels:
    app: booking-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
      version: v1
  template:
    metadata:
      labels:
        app: booking-service
        version: v1
    spec:
      containers:
      - name: booking-service
        image: task4-booking-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ENABLE_FEATURE_X
          value: "false"
        - name: VERSION
          value: "version1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-v2
  labels:
    app: booking-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
      version: v2
  template:
    metadata:
      labels:
        app: booking-service
        version: v2
    spec:
      containers:
      - name: booking-service
        imagePullPolicy: Never
        image: task4-booking-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENABLE_FEATURE_X
          value: "true"
        - name: VERSION
          value: "version2"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  selector:
    app: booking-service
  ports:
  - port: 80
    targetPort: 8080
