apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: booking-service
spec:
  hosts:
    - "*"
  gateways:
    - booking-gateway
  http:
  - match:
    - headers:
        x-route-to:
          exact: "v2"
    route:
    - destination:
        host: booking-service
        subset: v2
    
  - route:
    - destination:
        host: booking-service
        subset: v1
      weight: 90
    - destination:
        host: booking-service
        subset: v2
      weight: 10
    fault:
      abort:
        percentage:
          value: 0
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,gateway-error,connect-failure
      retryRemoteLocalities: true
