version: "3.8"

services:
  monolith:
    build:
      context: ../monolith
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 9090

  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotelio-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net
  
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "9090:9090"
      - "8085:8080"
    networks:
      - hotelio-net
    depends_on:
      kafka:
        condition: service_healthy
  
  booking-service-db:
    image: postgres:15
    container_name: booking-service-db
    environment:
      POSTGRES_USER: userhotelio
      POSTGRES_PASSWORD: passhotelio
      POSTGRES_DB: booking_service
    ports:
      - "5433:5432"
    volumes:
      - booking-service-db-data:/var/lib/postgresql/data
      - ./init-scripts/02-init-db-bookings.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hotelio-net
  
  booking-history-service:
    build: 
      context: ./booking-history-service
      dockerfile: Dockerfile
    container_name: booking-history-service
    networks:
      - hotelio-net
    depends_on:
      kafka:
        condition: service_healthy
  
  booking-history-db:
    image: postgres:15
    container_name: booking-history-db
    environment:
      POSTGRES_USER: userhotelio
      POSTGRES_PASSWORD: passhotelio
      POSTGRES_DB: booking_history
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
      - ./init-scripts/01-init-db-bookings-history.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hotelio-net

volumes:
  monolith-db-data:
  booking-service-db-data:
  booking-history-db-data:

networks:
  hotelio-net:
    external: true
