replicaCount: 1

image:
  name: task4-booking-service
  tag: latest
  pullPolicy: Never

env:
  - name: ENABLE_FEATURE_X
    value: "false"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"


livenessProbe:

readinessProbe:

